// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzstij5d7VGsa36sOhQU6lWJf0xvZ8vCQ',
    appId: '1:154301927448:web:f52972ae6e9c674146336d',
    messagingSenderId: '154301927448',
    projectId: 'edufit-69',
    authDomain: 'edufit-69.firebaseapp.com',
    storageBucket: 'edufit-69.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2Ye5APMZeykGxtwdOIptI-SRlOUMQpk4',
    appId: '1:154301927448:ios:5105eca8d44c47ab46336d',
    messagingSenderId: '154301927448',
    projectId: 'edufit-69',
    storageBucket: 'edufit-69.firebasestorage.app',
    iosBundleId: 'com.example.edufit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzstij5d7VGsa36sOhQU6lWJf0xvZ8vCQ',
    appId: '1:154301927448:web:c5d4b5619f460aa846336d',
    messagingSenderId: '154301927448',
    projectId: 'edufit-69',
    authDomain: 'edufit-69.firebaseapp.com',
    storageBucket: 'edufit-69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Ye5APMZeykGxtwdOIptI-SRlOUMQpk4',
    appId: '1:154301927448:ios:5105eca8d44c47ab46336d',
    messagingSenderId: '154301927448',
    projectId: 'edufit-69',
    storageBucket: 'edufit-69.firebasestorage.app',
    iosBundleId: 'com.example.edufit',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnM8qhmbXCAPpqJFOB7V2LeA20iAnissA',
    appId: '1:154301927448:android:c39eef63abfdce3146336d',
    messagingSenderId: '154301927448',
    projectId: 'edufit-69',
    storageBucket: 'edufit-69.firebasestorage.app',
  );

}